name: HistSys Development CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '13.0.1' # The JDK version to make available on the path.
          java-package: jdk # (jre, jdk, or jdk+fx) - defaults to jdk
          architecture: x64 # (x64 or x86) - defaults to x64
      - run: mvn package -B

  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Dir
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          password: ${{ secrets.PASSWORD }}
#          KEY: ${{ secrets.SSHKEY2 }}
          script: |
            cd /histsys/dev
            rm -rf ./source_files
            mkdir -p ./source_files
            echo "ğŸ™ŠRemove Old Source Files Success"

      - name: Copy file via scp
        uses: appleboy/scp-action@master
#        env:
##          KEY: ${{ secrets.SSHKEY2 }}
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          password: ${{ secrets.PASSWORD }}
          source: "."
          target: "/histsys/dev/source_files"

      - name: Build App
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          password: ${{ secrets.PASSWORD }}
#          KEY: ${{ secrets.SSHKEY2 }}
          script: |
            export SPRING_PROFILES_ACTIVE=dev
            echo "===============================[Start Building]======================================"
            cd /histsys/dev/source_files
            mvn package -B
            if [ ! -f "./web/target/web-1.0-SNAPSHOT.jar" ];then
              echo "Error: Compile Fail, File web-1.0-SNAPSHOT.jar not exist."
              exit 1
            fi
            echo "ğŸ˜€Compile Success"
            echo "===============================[Stop Running]======================================"
            echo "Kill Old Process"
            pid0=$(netstat -anp | grep -w 8080 | sed -r 's#.* (.*)/.*#\1#' | head -n 1)
            echo "ğŸ˜€Killing pid: $pid0"
            [ -z "$pid0" ] || kill $pid0

      - name: Run App
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          password: ${{ secrets.PASSWORD }}
#          KEY: ${{ secrets.SSHKEY2 }}
          script: |
            export SPRING_PROFILES_ACTIVE=dev
            cd /histsys/dev/
            mkdir -p logs
            rm -rf ./app/
            mv source_files app
            cd ./app
            logpath=/histsys/dev/logs/$(date +"%Y-%m-%d@%H_%M_%S").log
            nohup java -jar web/target/web-1.0-SNAPSHOT.jar -Duser.timezone=GMT+8 > $logpath &
            echo "ğŸ¶Deploy Success"